[package]
name = "math_render"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "math_render_tests"
path = "tests/main.rs"

[lib]
name = "math_render"
path = "src/lib.rs"

[dependencies]
wgpu = "22.1.0"
winit = "0.30.5"
env_logger = "0.11.5"
log = "0.4"
